version: '3.8'
services:
  backend-etl:
    build: ./backend
    environment:
      - REDIS_HOST=redis-cache
    networks:
      - crypto-bridge

  dashboard:
    build: ./frontend
    ports:
      - "8502:8501"
    networks:
      - crypto-bridge

networks:
  crypto-bridge:
    external: true