version: '3.8'
services:
  backend-etl:
    build: ./backend
    depends_on:
      - redis-cache

  redis-cache:
    image: redis:alpine
    ports:
      - "6379:6379"

  dashboard:
    build: ./frontend
    ports:
      - "8501:8501"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis-cache